plugins {
    application
    id("org.graalvm.buildtools.native") version "1.1.14"
    id("edu.sc.seis.launch4j") version "4.0.0"
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    mainClass.set("ru.anseranser.jmkvpropedit.JMkvpropedit")
}

// Single source of truth for the application version: gradle.properties (version=...).
// Generates a BuildVersion constant so the runtime never hardcodes the version.
val appVersion = version.toString()

val generateBuildVersion = tasks.register("generateBuildVersion") {
    val outputDir = layout.buildDirectory.dir("generated/buildversion/java")
    val versionValue = appVersion
    inputs.property("appVersion", versionValue)
    outputs.dir(outputDir)
    doLast {
        val pkgDir = outputDir.get().asFile.resolve("ru/anseranser/jmkvpropedit")
        pkgDir.mkdirs()
        pkgDir.resolve("BuildVersion.java").writeText(
            """
            package ru.anseranser.jmkvpropedit;

            /**
             * Generated by the {@code generateBuildVersion} Gradle task.
             * Do not edit — the version lives in gradle.properties ({@code version=...}).
             */
            public final class BuildVersion {

                public static final String VERSION = "$versionValue";

                private BuildVersion() {
                }
            }
            """.trimIndent()
        )
    }
}

sourceSets {
    main {
        java.srcDir(generateBuildVersion)
    }
}

tasks.withType<JavaCompile> {
    options.compilerArgs.add("-Xlint:deprecation")
}



dependencies {
    implementation("commons-io:commons-io:2.22.0")
    implementation("org.ini4j:ini4j:0.5.4")
}

graalvmNative {
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(21))
                vendor.set(JvmVendorSpec.GRAAL_VM)
            })
            imageName.set("jmkvpropedit")
            useFatJar.set(true)
        }
    }
}

launch4j {
    mainClassName = "ru.anseranser.jmkvpropedit.JMkvpropedit"
    outfile = "jmkvpropedit.exe"
}
